export const COMPETITION_STATS = [
  {
    icon: "Gamepad2",
    value: "42",
    label: "Live Competitions",
    sub: "Enter now",
  },
  { icon: "Gift", value: "128", label: "Total Prizes", sub: "Up for grabs" },
  { icon: "Trophy", value: "3.2K", label: "Participants", sub: "Joining in" },
  { icon: "Medal", value: "85", label: "Medal", sub: "So far" },
];

export const COMPETITION_TABS = [
  "All Competitions",
  "Live Now",
  "Ending Soon",
  "New Added",
];

export const COMPETITION_CATEGORIES = [
  "All Categories",
  "Music",
  "Gaming",
  "Sports",
  "Food & Drink",
  "Arts",
];

export const COMPETITION_SORT = [
  "Ending Soon",
  "Newest First",
  "Most Popular",
  "Least Entries",
];

export const COMPETITIONS_LIST = [
  {
    id: "imagine-dragons-vip",
    category: "Music",
    image:
      "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?auto=format&fit=crop&w=600&q=80",
    prizeSmall: "2 VIP TICKETS",
    prizeLarge: "IMAGINE DRAGONS",
    prizeItalic: "Live in Dublin",
    description: "Win 2 VIP Tickets to Imagine Dragons Live",
    organizer: "Imagine Dragons",
    participants: "3.4K",
    days: "01",
    hours: "06",
    mins: "31",
    secs: "01",
    isLive: true,
  },
  {
    id: "gaming-chair-bundle",
    category: "Gaming",
    image:
      "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?auto=format&fit=crop&w=600&q=80",
    prizeSmall: "WIN A",
    prizeLarge: "GAMING CHAIR",
    prizeItalic: "+ Accessories",
    description: "Win Premium Gaming Setup Bundle",
    organizer: "PlayArena",
    participants: "1.8K",
    days: "01",
    hours: "00",
    mins: "06",
    secs: "22",
    isLive: true,
  },
  {
    id: "backstage-pass-script",
    category: "Music",
    image:
      "https://images.unsplash.com/photo-1730875648117-ff32ae9b98c3?q=80&w=870&auto=format&fit=crop",
    prizeSmall: "BACKSTAGE PASS",
    prizeLarge: "THE SCRIPT",
    prizeItalic: "Meet & Greet",
    description: "Meet & Greet + Backstage Pass with The Script",
    organizer: "The Script",
    participants: "2.1K",
    days: "00",
    hours: "06",
    mins: "31",
    secs: "45",
    isLive: true,
  },
  {
    id: "signed-jersey-dublin-fc",
    category: "Sports",
    image:
      "https://images.unsplash.com/photo-1660260091479-10f5555ef462?q=80&w=870&auto=format&fit=crop",
    prizeSmall: "SIGNED JERSEY",
    prizeLarge: "DUBLIN FC",
    prizeItalic: "+ Match Tickets",
    description: "Signed Jersey + 2 Match Tickets",
    organizer: "Dublin FC",
    participants: "1.2K",
    days: "00",
    hours: "00",
    mins: "31",
    secs: "09",
    isLive: true,
  },
  {
    id: "festival-vip-experience",
    category: "Music",
    image:
      "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=600&q=80",
    prizeSmall: "FESTIVAL VIP",
    prizeLarge: "ELECTRIC PICNIC",
    prizeItalic: "Weekend Pass",
    description: "Win a VIP Weekend Pass to Electric Picnic",
    organizer: "Electric Picnic",
    participants: "4.5K",
    days: "03",
    hours: "12",
    mins: "00",
    secs: "00",
    isLive: true,
  },
  {
    id: "restaurant-experience",
    category: "Food & Drink",
    image:
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=600&q=80",
    prizeSmall: "FINE DINING",
    prizeLarge: "CHAPTER ONE",
    prizeItalic: "Experience for 2",
    description: "Exclusive 7-Course Tasting Menu for Two",
    organizer: "Chapter One",
    participants: "890",
    days: "05",
    hours: "08",
    mins: "00",
    secs: "00",
    isLive: false,
  },
  {
    id: "spa-weekend",
    category: "Arts",
    image:
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=600&q=80",
    prizeSmall: "SPA WEEKEND",
    prizeLarge: "FARNHAM ESTATE",
    prizeItalic: "For Two",
    description: "Luxury Spa Retreat Weekend at Farnham Estate",
    organizer: "Farnham Estate",
    participants: "2.3K",
    days: "07",
    hours: "00",
    mins: "45",
    secs: "30",
    isLive: false,
  },
  {
    id: "ps5-bundle",
    category: "Gaming",
    image:
      "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=600&q=80",
    prizeSmall: "WIN A",
    prizeLarge: "PS5 PRO",
    prizeItalic: "+ 3 Games",
    description: "PlayStation 5 Pro Bundle with Top Titles",
    organizer: "GameZone IE",
    participants: "6.1K",
    days: "00",
    hours: "02",
    mins: "15",
    secs: "55",
    isLive: true,
  },
];