// Mock data for /my-events. Swap for real API data once bookings endpoints exist.

export const MY_EVENTS_STATS = [
  {
    key: "upcoming",
    icon: "Calendar",
    count: 16,
    label: "Upcoming",
    sub: "Next: The Script 22 Aug 2026",
  },
  {
    key: "booked",
    icon: "Ticket",
    count: 32,
    label: "Booked",
    sub: "All confirmed bookings",
  },
  {
    key: "past",
    icon: "Clock",
    count: 24,
    label: "Past Events",
    sub: "Events you've attended",
  },
  {
    key: "cancelled",
    icon: "XCircle",
    count: 6,
    label: "Cancelled",
    sub: "Bookings that were cancelled",
  },
];

export const MY_EVENTS_TABS = [
  { key: "upcoming", label: "Upcoming" },
  { key: "booked", label: "Booked" },
  { key: "past", label: "Past" },
  { key: "cancelled", label: "Cancelled" },
];

const img = (id) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=500&q=80`;

export const MY_EVENTS_BY_TAB = {
  upcoming: [
    {
      id: "the-script",
      image: img("photo-1470225620780-dba8ba36b745"),
      badge: "UPCOMING",
      dateMonth: "AUG",
      dateDay: "22",
      title: "The Script",
      subtitle: "Greatest Hits Tour",
      venue: "3Arena, Dublin",
      time: "Sat, 22 Aug 2026 · 8:00 PM",
    },
    {
      id: "dublin-food-fest",
      image: img("photo-1414235077428-338989a2e8c0"),
      badge: "UPCOMING",
      dateMonth: "AUG",
      dateDay: "29",
      title: "Dublin Food Fest",
      subtitle: "Taste the City",
      venue: "Iveagh Gardens, Dublin",
      time: "Sat, 29 Aug 2026 · 12:00 PM",
    },
    {
      id: "neon-nights",
      image: img("photo-1516450360452-9312f5e86fc7"),
      badge: "UPCOMING",
      dateMonth: "SEP",
      dateDay: "05",
      title: "Neon Nights",
      subtitle: "Summer Club Series",
      venue: "The Grand Social, Dublin",
      time: "Fri, 5 Sep 2026 · 11:00 PM",
    },
    {
      id: "back-to-90s",
      image: img("photo-1470229722913-7c0e2dbbafd3"),
      badge: "UPCOMING",
      dateMonth: "SEP",
      dateDay: "12",
      title: "Back To 90s",
      subtitle: "Retro Club Night",
      venue: "Button Factory, Dublin",
      time: "Sat, 12 Sep 2026 · 11:00 PM",
    },
  ],
  booked: [
    {
      id: "sam-fender",
      image: img("photo-1493225457124-a3eb161ffa5f"),
      badge: "BOOKED",
      dateMonth: "AUG",
      dateDay: "03",
      title: "Sam Fender",
      subtitle: "Live in Dublin",
      venue: "3Arena, Dublin",
      time: "Mon, 3 Aug 2026 · 7:30 PM",
    },
    {
      id: "electric-fields",
      image: img("photo-1470229722913-7c0e2dbbafd3"),
      badge: "BOOKED",
      dateMonth: "AUG",
      dateDay: "09",
      title: "Electric Fields",
      subtitle: "Summer Festival",
      venue: "Marlay Park, Dublin",
      time: "Sun, 9 Aug 2026 · 1:00 PM",
    },
    {
      id: "comedy-night",
      image: img("photo-1585699324551-f6c309eedeca"),
      badge: "BOOKED",
      dateMonth: "AUG",
      dateDay: "12",
      title: "Comedy Night",
      subtitle: "Stand-up Special",
      venue: "Vicar St, Dublin",
      time: "Wed, 12 Aug 2026 · 8:00 PM",
    },
  ],
  past: [
    {
      id: "modern-art",
      image: img("photo-1554907984-15263bfd63bd"),
      badge: "PAST",
      dateMonth: "JUN",
      dateDay: "14",
      title: "Modern Art",
      subtitle: "Exhibition Opening",
      venue: "IMMA, Dublin",
      time: "Sun, 14 Jun 2026 · 6:00 PM",
    },
    {
      id: "wild-waves-fest",
      image: img("photo-1459749411175-04bf5292ceea"),
      badge: "PAST",
      dateMonth: "MAY",
      dateDay: "02",
      title: "Wild Waves Fest",
      subtitle: "Coastal Concert Series",
      venue: "Bray Seafront, Dublin",
      time: "Sat, 2 May 2026 · 6:30 PM",
    },
  ],
  cancelled: [
    {
      id: "rooftop-sessions",
      image: img("photo-1501281668745-f7f57925c3b4"),
      badge: "CANCELLED",
      dateMonth: "JUL",
      dateDay: "20",
      title: "Rooftop Sessions",
      subtitle: "Summer Series",
      venue: "The Marker, Dublin",
      time: "Mon, 20 Jul 2026 · 9:00 PM",
    },
  ],
};
