import {
  Menu,
  X,
  Search,
  User,
  ChevronDown,
  ChevronRight,
  PartyPopper,
  Trophy,
  Users,
  ArrowLeftRight,
  Paperclip,
  Zap,
  Flag,
  ArrowRight,
  MessageCircle,
  MapPin,
  Calendar,
  LayoutGrid,
  Tag,
  SlidersHorizontal,
  Heart,
  ChevronLeft,
  Flame,
  Ticket,
  Share2,
  Music,
  Smile,
  Tent,
  CircleDot,
  Drama,
  Coffee,
  PenLine,
  MoreHorizontal,
  Volleyball,
  Sparkle,
  QrCode,
  Apple,
  Play,
  Check,
  CircleX,
  TriangleAlert,
  Info,
  Mail,
  Martini,
  Palette,
  Bell,
  Settings,
  Shield,
  Lock,
  CreditCard,
  Globe,
  LogOut,
  HelpCircle,
  Camera,
  Eye,
  EyeOff,
  Smartphone,
  Link2,
  Wallet,
  ShieldCheck,
  Moon,
  Edit2,
  Trash2,
  Plus,
  Clock,
  XCircle,
  Filter,
  Briefcase,
  Gamepad2,
  UtensilsCrossed,
  Lightbulb,
  Sparkles,
  Baby,
  TreePine,
  Gift,
  Medal,
  UserCircle,
  CircleDollarSign,
  Download,
  BookOpen,
  Send,
  ClipboardList,
  RefreshCcw,
  Headphones,
  Phone,
  ArrowLeft,
  Quote,
  Star,
  Activity,
  UserPlus
} from "lucide-react";

import Logo from "./Logo";
import { Facebook, Instagram, Linkedin, TikTok } from "./Social";
import { QuoteIcon } from "./Quotes";

export const LUCIDE_ICONS = {
  Menu: Menu,
  X: X,
  Search: Search,
  User: User,
  ChevronDown: ChevronDown,
  ChevronRight: ChevronRight,
  PartyPopper: PartyPopper,
  Trophy: Trophy,
  Users: Users,
  ArrowLeftRight: ArrowLeftRight,
  Paperclip: Paperclip,
  Zap: Zap,
  ArrowRight: ArrowRight,
  MessageCircle: MessageCircle,
  MapPin: MapPin,
  Calendar: Calendar,
  LayoutGrid: LayoutGrid,
  Tag: Tag,
  SlidersHorizontal: SlidersHorizontal,
  Heart: Heart,
  ChevronLeft: ChevronLeft,
  Flame: Flame,
  Ticket: Ticket,
  Share2: Share2,
  Music: Music,
  Smile: Smile,
  Tent: Tent,
  CircleDot: CircleDot,
  Drama: Drama,
  Coffee: Coffee,
  PenLine: PenLine,
  MoreHorizontal: MoreHorizontal,
  Volleyball: Volleyball,
  Sparkle: Sparkle,
  Sparkles: Sparkles,
  QrCode: QrCode,
  Apple: Apple,
  Play: Play,
  Check: Check,
  CircleX: CircleX,
  TriangleAlert: TriangleAlert,
  Info: Info,
  Mail: Mail,
  Martini: Martini,
  Palette: Palette,
  Bell: Bell,
  Settings: Settings,
  Shield: Shield,
  Lock: Lock,
  CreditCard: CreditCard,
  Globe: Globe,
  LogOut: LogOut,
  HelpCircle: HelpCircle,
  Camera: Camera,
  Eye: Eye,
  EyeOff: EyeOff,
  Smartphone: Smartphone,
  Link2: Link2,
  Wallet: Wallet,
  ShieldCheck: ShieldCheck,
  Moon: Moon,
  Edit2: Edit2,
  Trash2: Trash2,
  Plus: Plus,
  Clock: Clock,
  Flag: Flag,
  XCircle: XCircle,
  Filter: Filter,
  Briefcase: Briefcase,
  Gamepad2: Gamepad2,
  UtensilsCrossed: UtensilsCrossed,
  Lightbulb: Lightbulb,
  Baby: Baby,
  TreePine: TreePine,
  Gift: Gift,
  Medal: Medal,
  UserCircle: UserCircle,
  CircleDollarSign: CircleDollarSign,
  Download: Download,
  BookOpen: BookOpen,
  Send: Send,
  ClipboardList: ClipboardList,
  RefreshCcw: RefreshCcw,
  Headphones: Headphones,
  Phone: Phone,
  ArrowLeft: ArrowLeft,
  Quote: Quote,
  Star: Star,
  Activity: Activity,
  UserPlus: UserPlus
};

export const ICONS_MAP = {
  Logo: Logo,
  Facebook: Facebook,
  Instagram: Instagram,
  Linkedin: Linkedin,
  TikTok: TikTok,
  Quotes: QuoteIcon
};  